SELECT distinct ?item ?itemLabel ?date ?end ?start ?country WHERE {

  ?item wdt:P31/wdt:P279* wd:Q744913. #aviation accident
  
  ?item wdt:P1561 ?filterProperty. #survivors
  FILTER ( ?filterProperty > 100 )
  
  ?item wdt:P137 ?operator.
  ?operator wdt:P17 wd:Q30. #USA

  
  Optional { ?item wdt:P582 ?end.}
  Optional { ?item wdt:P585 ?date.}
  Optional { ?item wdt:P580 ?start.}
  
  { ?item wdt:P585 ?w585. BIND (?w585 as ?w)} UNION { ?item wdt:P580 ?w580. BIND (?w580 as ?w)
       }                                           
  FILTER ( YEAR(?w) >= 1987 )
  FILTER ( YEAR(?w) <= 2007)
  

    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

}
ORDER BY ASC(?w)
