SELECT distinct ?item ?itemLabel ?date ?sum WHERE {

  ?item wdt:P31/wdt:P279* wd:Q32096.
  #?item wdt:P1346 ?winner.
  #?winner wdt:P571 ?inception.
  #FILTER ( YEAR(?inception) > 1950)
  
  { SELECT (SUM(?a) as ?sum) ?item WHERE {
    ?item p:P1923   ?s  .  # ?s is the the statement node
           ?s  pq:P1351 ?a  .  # this is an attribute (a qualifier) 
     } group by ?item
   }
  FILTER (?sum > 50)
  
  Optional { ?item wdt:P582 ?end.}
  Optional { ?item wdt:P585 ?date.}
  Optional { ?item wdt:P580 ?start.}
  
  { ?item wdt:P585 ?w585. BIND (?w585 as ?w)} UNION { ?item wdt:P580 ?w580. BIND (?w580 as ?w)
       }                                           
  FILTER ( YEAR(?w) >= 1987 )
  FILTER ( YEAR(?w) <= 2007)
  

    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

}
ORDER BY ASC(?w)
