SELECT ?player ?playerLabel ?totalMatchesPlayed {

SERVICE wikibase:label {bd:serviceParam wikibase:language "en" . }

{
  SELECT ?player (sum(?matchesPlayed) as ?totalMatchesPlayed) WHERE {
    ?player wdt:P106/wdt:P279* wd:Q937857 . 
    ?player   p:P54/pq:P1350 ?matchesPlayed.
  }
  GROUP BY ?player
  LIMIT 100
}

}
