SELECT ?itemLabel ?start ?end WHERE {

   ?item wdt:P31 wd:Q5 .
   ?item [RELATION] ?position_held_statement .
   ?position_held_statement ps:P39 [ENTITY] .
  
   ?position_held_statement pq:P580 ?start .
   ?position_held_statement pq:P582 ?end .

  # filter by start date here
  FILTER(year(?end) >= 1987)
  FILTER(year(?start) <= 2007)

   SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
   }

 } ORDER BY ?start
