# stock-listed US companies with founders who (or whose parents) were born outside the US
SELECT ?companyLabel (GROUP_CONCAT(DISTINCT ?founderLabel; separator=", ") AS ?founders) WHERE {
  ?company wdt:P112 ?founder;
           wdt:P17 wd:Q30.
  FILTER EXISTS { ?company wdt:P414|wdt:P249 []. }
  OPTIONAL { ?founder rdfs:label ?founderLabel. FILTER(LANG(?founderLabel) = "en"). }
  OPTIONAL { ?company wdt:P2403|wdt:P2137|wdt:P2139|wdt:P2226|wdt:P2295 ?money. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
GROUP BY ?companyLabel
ORDER BY DESC(MAX(?money)) ?companyLabel
